# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 316246421);
user_pref("app.update.migrated.updateDir", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 24);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.isUS", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20141126041045");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 8157);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20141126041045");
user_pref("browser.startup.homepage_override.mstone", "34.0.5");
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("browser.uitour.treatment.srch-chg-action", "ViewPage");
user_pref("browser.uitour.treatment.srch-chg-treatment", "whatsnew_Default");
user_pref("browser.uitour.whitelist.add.260", "");
user_pref("browser.uitour.whitelist.add.340", "");
user_pref("browser.uitour.whitelist.add.341", "");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1416689096637");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1417626432744");
user_pref("datareporting.policy.firstRunTime", "1416602696637");
user_pref("datareporting.sessions.current.activeTicks", 7);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 11343);
user_pref("datareporting.sessions.current.main", 1621);
user_pref("datareporting.sessions.current.sessionRestored", 11536);
user_pref("datareporting.sessions.current.startTime", "1417626411163");
user_pref("datareporting.sessions.current.totalTime", 44);
user_pref("datareporting.sessions.currentIndex", 5);
user_pref("datareporting.sessions.previous.0", "{\"s\":1416602695783,\"a\":11,\"t\":53,\"c\":true,\"m\":515,\"fp\":1813,\"sr\":1891}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1416602880586,\"a\":5,\"t\":24,\"c\":true,\"m\":469,\"fp\":1158,\"sr\":1205}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1417290789431,\"a\":3,\"t\":17,\"c\":true,\"m\":1244,\"fp\":2404,\"sr\":2605}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1417457353699,\"a\":1,\"t\":26,\"c\":true,\"m\":6467,\"fp\":22440,\"sr\":22659}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1417479398107,\"a\":4,\"t\":45,\"c\":true,\"m\":1995,\"fp\":33802,\"sr\":4887}");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:34.0.5");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1417626393248,\"rdfTime\":1417010916000}}}]");
user_pref("extensions.lastAppVersion", "34.0.5");
user_pref("extensions.lastPlatformVersion", "34.0.5");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20141126041045");
user_pref("gecko.mstone", "34.0.5");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("loop.soft_start_ticket_number", 1721149);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 77157);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("pref.general.disable_button.default_browser", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1417626412);
user_pref("toolkit.telemetry.previousBuildID", "20141126041045");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1419194699);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
