#!/bin/bash

# MUST BE RUN AS "sudo bash scriptname"

#ip=echo `ifconfig eth0 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://'`

ip=$(ifconfig eth0 | awk -F"[: ]+" '/inet addr:/ {print $4}')

first=192
second=168
thirdHQ='([0-3])'
thirdTower='([10]{2}[4-8]{1})'
thirdProvo='([8-9]|1[0-1])'
thirdRoy='(1[6-9])'
thirdSAT='(20[8-9]|21[0-1])'
fourth='([0-9]{1,3})'

#for ip in 192.168.1.25 192.168.108.10 192.168.105.155 \
#       192.168.16.1 192.168.19.199\
#       192.168.8.9 192.168.10.91 192.168.11.19 \
#       192.168.211.255 192.168.208.1 192.168.210.29; do

if [[ $ip =~ ^$first\.$second\.$thirdHQ\.$fourth$ ]]; then
        echo "valid HQ:     "$ip
        serverIP='192.168.106.19'
        serverName='ucs-tower-1.connexionpoint.local'
        echo $serverIP
        echo $serverName

elif [[ $ip =~ ^$first\.$second\.$thirdTower\.$fourth$ ]]; then
        echo "valid Tower:     "$ip
	serverIP='192.168.106.19'
	serverName='ucs-tower-1.connexionpoint.local'
	echo $serverIP
	echo $serverName

elif [[ $ip =~ ^$first\.$second\.$thirdProvo\.$fourth$ ]]; then
        echo "valid Provo:     "$ip
	serverIP='192.168.8.19'
        serverName='ucs-provo-1.connexionpoint.local'
        echo $serverIP
        echo $serverName

elif [[ $ip =~ ^$first\.$second\.$thirdRoy\.$fourth$ ]]; then
        echo "valid Roy:     "$ip
	serverIP='192.168.16.19'
        serverName='ucs-roy-1.connexionpoint.local'
        echo $serverIP
        echo $serverName

elif [[ $ip =~ ^$first\.$second\.$thirdSAT\.$fourth$ ]]; then
        echo "valid SAT:     "$ip
	echo "Will add more in here when we have a SAT Univention server"
	#exit(1)
else
        echo "not valid: "$ip
fi
#done

sed -i "s/URI ldap:\/\/ucs-main.connexionpoint.local:7389/URI ldap:\/\/$serverName:7389 ldap:\/\/ucs-main.connexionpoint.local:7389/g" /etc/ldap/ldap.conf

cat /etc/ldap/ldap.conf

sed -i "s/krb5_server = ucs-main.connexionpoint.local/krb5_server = $serverName,ucs-main.connexionpoint.local/g" /etc/sssd/sssd.conf

sed -i "s/ldap_uri = ldap:\/\/ucs-main.connexionpoint.local:7389/ldap_uri = ldap:\/\/$serverName:7389,ldap:\/\/ucs-main.connexionpoint.local:7389/g" /etc/sssd/sssd.conf 

cat /etc/sssd/sssd.conf

sed -i "s/   kdc = 192.168.128.239 ucs-main.connexionpoint.local/   kdc = $serverIP $serverName 192.168.128.239 ucs-main.connexionpoint.local/g" /etc/krb5.conf

cat /etc/krb5.conf

sed -i "/#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN/a nameserver $serverIP" /etc/resolvconf/resolv.conf.d/head

cat /etc/resolvconf/resolv.conf.d/head
