#!/bin/bash
#echo "Configuring resolveconf for persistent nameserver settings..."
#echo "nameserver 192.168.128.239" >> /etc/resolvconf/resolv.conf.d/head
#echo "nameserver 8.8.8.8" >> /etc/resolvconf/resolv.conf.d/head
#resolvconf -u
#cat /etc/resolv.conf

echo '# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 192.168.128.239
nameserver 8.8.8.8' > /etc/resolvconf/resolv.conf.d/head
resolvconf -u
cat /etc/resolv.conf
