try{
'use strict';var l,n=this,q=function(a){a.B=function(){return a.S?a.S:a.S=new a}},aa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&
"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},r=function(a){return"array"==aa(a)},ba=function(a){var b=aa(a);return"array"==b||"object"==b&&"number"==typeof a.length},u=function(a){return"string"==typeof a},ca=function(a){return"function"==aa(a)},da=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},ga=function(a){return a[ea]||(a[ea]=++fa)},
ea="closure_uid_"+(1E9*Math.random()>>>0),fa=0,ha=function(a,b,c){return a.call.apply(a.bind,arguments)},ia=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},w=function(a,b,c){w=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ha:ia;return w.apply(null,
arguments)},ja=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},x=Date.now||function(){return+new Date},y=function(a,b){function c(){}c.prototype=b.prototype;a.H=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.X=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};
var z=function(){this.i=this.i;this.h=this.h};z.prototype.i=!1;z.prototype.R=function(){this.i||(this.i=!0,this.g())};var ka=function(a,b){a.i?b.call(void 0):(a.h||(a.h=[]),a.h.push(b))};z.prototype.g=function(){if(this.h)for(;this.h.length;)this.h.shift()()};var la=function(a){a&&"function"==typeof a.R&&a.R()};
var A=function(a,b){this.type=a;this.a=this.target=b;this.U=!0};A.prototype.g=function(){this.U=!1};var ma=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},ua=function(a){if(!na.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(oa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(pa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(qa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ra,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(sa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(ta,"&#0;"));return a},oa=/&/g,pa=/</g,qa=/>/g,ra=/"/g,sa=/'/g,ta=/\x00/g,na=/[\x00&<>"']/,
wa=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'},c;c=n.document.createElement("div");return a.replace(va,function(a,e){var f=b[a];if(f)return f;if("#"==e.charAt(0)){var g=Number("0"+e.substr(1));isNaN(g)||(f=String.fromCharCode(g))}f||(c.innerHTML=a+" ",f=c.firstChild.nodeValue.slice(0,-1));return b[a]=f})},xa=function(a){return a.replace(/&([^;]+);/g,function(a,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if("#"==c.charAt(0)){var d=
Number("0"+c.substr(1));if(!isNaN(d))return String.fromCharCode(d)}return a}})},va=/&([^;\s<&]+);?/g,B=function(a){return null==a?"":String(a)},ya=function(a,b){return a<b?-1:a>b?1:0},za=function(a){isFinite(a)&&(a=String(a));return u(a)?/^\s*-?0x/i.test(a)?parseInt(a,16):parseInt(a,10):NaN};
var Aa=function(a){A.call(this,a);this.h=0;this.c=null;this.l=this.o="";this.s=0;this.i=""};y(Aa,A);var Ba=function(a,b,c,d,e){var f=new Aa("clip_changed");f.c=a;f.h=b;f.o=c;f.l=d;e&&(f.s=e.i,f.i=e.A());return f};Aa.prototype.D=function(){return B(this.c&&this.c.A()||null)};
var Ca;var C=Array.prototype,Da=C.indexOf?function(a,b,c){return C.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(u(a))return u(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ea=C.forEach?function(a,b,c){C.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=u(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Fa=C.filter?function(a,b,c){return C.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=u(a)?
a.split(""):a,h=0;h<d;h++)if(h in g){var k=g[h];b.call(c,k,h,a)&&(e[f++]=k)}return e},Ga=C.map?function(a,b,c){return C.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=u(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e},Ha=function(a){return C.concat.apply(C,arguments)},Ia=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Ja=function(a,b){for(var c=b||function(){return da(g)?"o"+ga(g):(typeof g).charAt(0)+g},d={}, e=0,f=0;f<a.length;){var g=a[f++],h=c(g);Object.prototype.hasOwnProperty.call(d,h)||(d[h]=!0,a[e++]=g)}a.length=e},Ka=function(a,b){return a>b?1:a<b?-1:0};
var La=n.JSON.stringify;var Ma=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Na=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Oa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Pa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Oa.length;f++)c=Oa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}},Qa=function(a){var b=arguments.length;if(1==b&&r(arguments[0]))return Qa.apply(null, arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};
var D=function(){},E=function(a,b,c,d){a.a=null;b||(b=[]);a.l=void 0;a.i=-1;a.c=b;a:{if(a.c.length){b=a.c.length-1;var e=a.c[b];if(e&&"object"==typeof e&&!r(e)){a.h=b-a.i;a.g=e;break a}}-1<c?(a.h=c,a.g=null):a.h=Number.MAX_VALUE}if(d)for(c=0;c<d.length;c++)b=d[c],b<a.h?(b+=a.i,a.c[b]=a.c[b]||Ra):a.g[b]=a.g[b]||Ra},Ra=[],F=function(a,b){if(b<a.h){var c=b+a.i,d=a.c[c];return d===Ra?a.c[c]=[]:d}d=a.g[b];return d===Ra?a.g[b]=[]:d},G=function(a,b,c){b<a.h?a.c[b+a.i]=c:a.g[b]=c},H=function(a,b,c){a.a||
(a.a={});if(!a.a[c]){var d=F(a,c);d&&(a.a[c]=new b(d))}return a.a[c]},I=function(a,b,c){a.a||(a.a={});var d=c?c.c:c;a.a[b]=c;G(a,b,d)};D.prototype.m=function(){return n.JSON&&n.JSON.stringify?n.JSON.stringify(this.c):La(this.c)};D.prototype.toString=function(){return this.c.toString()};
var Ta=function(a){var b=Sa;if(a.g){a.a||(a.a={});var c=b.c;if(b.g){if(b.a)return a.a[c]||(a.a[c]=Ga(a.g[c]||[],function(a){return new b.a(a)})),a.a[c]}else if(b.a)return!a.a[c]&&a.g[c]&&(a.a[c]=new b.a(a.g[c])),a.a[c];return a.g[c]}},Ua=function(a){var b;if(r(a)){for(var c=Array(a.length),d=0;d<a.length;d++)null!=(b=a[d])&&(c[d]="object"==typeof b?Ua(b):b);return c}c={};for(d in a)null!=(b=a[d])&&(c[d]="object"==typeof b?Ua(b):b);return c};
var Wa=function(a){E(this,a,-1,Va)};y(Wa,D);var Va=[3];Wa.prototype.getTitle=function(){return F(this,2)};Wa.prototype.setTitle=function(a){G(this,2,a)};var Xa=function(a){this.a=a||new Wa};Xa.prototype.setTitle=function(a){this.a.setTitle(a)};Xa.prototype.m=function(){return this.a.m()};var Ya=function(a){E(this,a,-1,null)};y(Ya,D);var K=function(a){return H(a,J,2)},J=function(a){E(this,a,-1,null)};y(J,D);var Za=function(a){return F(a,1)};var $a=function(a){E(this,a,-1,null)};y($a,D);$a.prototype.A=function(){return F(this,1)};var ab=function(a){E(this,a,-1,null)};y(ab,D);ab.prototype.getTitle=function(){return F(this,1)};ab.prototype.setTitle=function(a){G(this,1,a)};var bb=function(a){E(this,a,-1,null)};y(bb,D);var cb=function(a){E(this,a,-1,null)};y(cb,D);var eb=function(a){E(this,a,22,db)};y(eb,D);var db=[3];eb.prototype.D=function(){return H(this,$a,1)};var fb=function(a){E(this,a,-1,null)};y(fb,D);var gb=function(a){this.a=a||new fb};gb.prototype.m=function(){return this.a.m()};var hb;a:{var ib=n.navigator;if(ib){var jb=ib.userAgent;if(jb){hb=jb;break a}}hb=""}var L=function(a){return-1!=hb.indexOf(a)};var lb=function(){return L("Opera")||L("OPR")},mb=function(){return L("Edge")||L("Trident")||L("MSIE")},nb=function(){return(L("Chrome")||L("CriOS"))&&!lb()&&!mb()};var M=function(){return L("Edge")};var ob=lb(),N=mb(),pb=L("Gecko")&&!(-1!=hb.toLowerCase().indexOf("webkit")&&!M())&&!(L("Trident")||L("MSIE"))&&!M(),qb=-1!=hb.toLowerCase().indexOf("webkit")&&!M(),rb=function(){var a=hb;if(pb)return/rv\:([^\);]+)(\)|;)/.exec(a);if(N&&M())return/Edge\/([\d\.]+)/.exec(a);if(N)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(qb)return/WebKit\/(\S+)/.exec(a)},sb=function(){var a=n.document;return a?a.documentMode:void 0},tb=function(){if(ob&&n.opera){var a=n.opera.version;return ca(a)?a():a}var a=
"",b=rb();b&&(a=b?b[1]:"");return N&&!M()&&(b=sb(),b>parseFloat(a))?String(b):a}(),ub={},O=function(a){var b;if(!(b=ub[a])){b=0;for(var c=ma(String(tb)).split("."),d=ma(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",k=/(\d*)(\D*)/g,p=/(\d*)(\D*)/g;do{var m=k.exec(g)||["","",""],t=p.exec(h)||["","",""];if(0==m[0].length&&0==t[0].length)break;b=ya(0==m[1].length?0:parseInt(m[1],10),0==t[1].length?0:parseInt(t[1],10))||ya(0==m[2].length,0==t[2].length)|| ya(m[2],t[2])}while(0==b)}b=ub[a]=0<=b}return b},wb=function(){return N&&(M()||9<=vb)},xb=n.document,yb=sb(),vb=!xb||!N||!yb&&M()?void 0:yb||("CSS1Compat"==xb.compatMode?parseInt(tb,10):5);
var zb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,Cb=function(a){if(Ab){Ab=!1;var b=n.location;if(b){var c=b.href;if(c&&(c=Bb(Cb(c)[3]||null))&&c!=b.hostname)throw Ab=!0,Error();}}return a.match(zb)},Ab=qb,Bb=function(a){return a?decodeURI(a):a},Db=function(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f=null,g=null;0<=e?(f=c[d].substring(0,e),g=c[d].substring(e+1)):f=c[d];b(f,g?decodeURIComponent(g.replace(/\+/g, " ")):"")}};
var Eb="StopIteration"in n?n.StopIteration:{message:"StopIteration",stack:""},Fb=function(){};Fb.prototype.next=function(){throw Eb;};Fb.prototype.N=function(){return this};var P=function(a,b){this.c={};this.a=[];this.h=this.g=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){if(a instanceof P)d=a.F(),c=a.v();else{var c=[],e=0;for(d in a)c[e++]=d;d=c;c=Na(a)}for(e=0;e<d.length;e++)this.set(d[e],c[e])}};P.prototype.v=function(){Gb(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.c[this.a[b]]);return a};P.prototype.F=function(){Gb(this);return this.a.concat()};
P.prototype.G=function(){return 0==this.g};P.prototype.remove=function(a){return Hb(this.c,a)?(delete this.c[a],this.g--,this.h++,this.a.length>2*this.g&&Gb(this),!0):!1};var Gb=function(a){if(a.g!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Hb(a.c,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.g!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],Hb(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};l=P.prototype;l.get=function(a,b){return Hb(this.c,a)?this.c[a]:b};
l.set=function(a,b){Hb(this.c,a)||(this.g++,this.a.push(a),this.h++);this.c[a]=b};l.forEach=function(a,b){for(var c=this.F(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};l.clone=function(){return new P(this)};l.N=function(a){Gb(this);var b=0,c=this.h,d=this,e=new Fb;e.next=function(){if(c!=d.h)throw Error("The map has changed since the iterator was created");if(b>=d.a.length)throw Eb;var e=d.a[b++];return a?e:d.c[e]};return e}; var Hb=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var Ib=function(a){if("function"==typeof a.v)return a.v();if(u(a))return a.split("");if(ba(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Na(a)};var Q=function(a,b){this.c=this.o=this.g="";this.s=null;this.h=this.a="";this.i=!1;var c;a instanceof Q?(this.i=void 0!==b?b:a.i,Jb(this,a.g),this.o=a.o,this.c=a.c,Kb(this,a.s),this.a=a.a,Lb(this,a.l.clone()),this.h=a.h):a&&(c=Cb(String(a)))?(this.i=!!b,Jb(this,c[1]||"",!0),this.o=Mb(c[2]||""),this.c=Mb(c[3]||"",!0),Kb(this,c[4]),this.a=Mb(c[5]||"",!0),Lb(this,c[6]||"",!0),this.h=Mb(c[7]||"")):(this.i=!!b,this.l=new R(null,0,this.i))};
Q.prototype.toString=function(){var a=[],b=this.g;b&&a.push(Nb(b,Ob,!0),":");if(b=this.c){a.push("//");var c=this.o;c&&a.push(Nb(c,Ob,!0),"@");a.push(encodeURIComponent(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.s;null!=b&&a.push(":",String(b))}if(b=this.a)this.c&&"/"!=b.charAt(0)&&a.push("/"),a.push(Nb(b,"/"==b.charAt(0)?Pb:Qb,!0));(b=this.l.toString())&&a.push("?",b);(b=this.h)&&a.push("#",Nb(b,Rb));return a.join("")};Q.prototype.clone=function(){return new Q(this)};
var Jb=function(a,b,c){a.g=c?Mb(b,!0):b;a.g&&(a.g=a.g.replace(/:$/,""))},Kb=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.s=b}else a.s=null},Lb=function(a,b,c){b instanceof R?(a.l=b,Sb(a.l,a.i)):(c||(b=Nb(b,Tb)),a.l=new R(b,0,a.i))},Ub=function(a){return a instanceof Q?a.clone():new Q(a,void 0)},Mb=function(a,b){return a?b?decodeURI(a):decodeURIComponent(a):""},Nb=function(a,b,c){return u(a)?(a=encodeURI(a).replace(b,Vb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,
"%$1")),a):null},Vb=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Ob=/[#\/\?@]/g,Qb=/[\#\?:]/g,Pb=/[\#\?]/g,Tb=/[\#\?@]/g,Rb=/#/g,R=function(a,b,c){this.g=this.a=null;this.c=a||null;this.h=!!c},S=function(a){a.a||(a.a=new P,a.g=0,a.c&&Db(a.c,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};R.prototype.add=function(a,b){S(this);this.c=null;a=Wb(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.g++;return this};
R.prototype.remove=function(a){S(this);a=Wb(this,a);return Hb(this.a.c,a)?(this.c=null,this.g-=this.a.get(a).length,this.a.remove(a)):!1};R.prototype.G=function(){S(this);return 0==this.g};var Xb=function(a,b){S(a);b=Wb(a,b);return Hb(a.a.c,b)};l=R.prototype;l.F=function(){S(this);for(var a=this.a.v(),b=this.a.F(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
l.v=function(a){S(this);var b=[];if(u(a))Xb(this,a)&&(b=Ha(b,this.a.get(Wb(this,a))));else{a=this.a.v();for(var c=0;c<a.length;c++)b=Ha(b,a[c])}return b};l.set=function(a,b){S(this);this.c=null;a=Wb(this,a);Xb(this,a)&&(this.g-=this.a.get(a).length);this.a.set(a,[b]);this.g++;return this};l.get=function(a,b){var c=a?this.v(a):[];return 0<c.length?String(c[0]):b};
l.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.F(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.v(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}return this.c=a.join("&")};l.clone=function(){var a=new R;a.c=this.c;this.a&&(a.a=this.a.clone(),a.g=this.g);return a};
var Wb=function(a,b){var c=String(b);a.h&&(c=c.toLowerCase());return c},Sb=function(a,b){b&&!a.h&&(S(a),a.c=null,a.a.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),this.remove(e),0<a.length&&(this.c=null,this.a.set(Wb(this,e),Ia(a)),this.g+=a.length))},a));a.h=b};
var Yb=function(a){this.a=a||new ab;a=F(this.a,3);G(this.a,3,a)};Yb.prototype.getTitle=function(){return B(this.a.getTitle())};Yb.prototype.setTitle=function(a){this.a.setTitle(a)};Yb.prototype.m=function(){return this.a.m()};Qa("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));var Zb=function(){this.c="";this.a=null},$b=function(a){var b=new Zb;b.c=a;b.a=0};$b("<!DOCTYPE html>");$b("");var ac=function(a){this.a=new P;if(a){a=Ib(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])}},bc=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+ga(a):b.substr(0,1)+a};l=ac.prototype;l.add=function(a){this.a.set(bc(a),a)};l.removeAll=function(a){a=Ib(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};l.remove=function(a){return this.a.remove(bc(a))};l.G=function(){return this.a.G()};l.v=function(){return this.a.v()};l.clone=function(){return new ac(this)};l.N=function(){return this.a.N(!1)};
var cc=function(a,b,c,d,e){this.reset(a,b,c,d,e)};cc.prototype.a=null;var dc=0;cc.prototype.reset=function(a,b,c,d,e){"number"==typeof e||dc++;this.g=d||x();this.h=a;this.i=b;this.c=c;delete this.a};cc.prototype.getMessage=function(){return this.i};var ec=function(a){this.h=a;this.c=this.g=this.a=null},hc=function(a,b){this.name=a;this.value=b};hc.prototype.toString=function(){return this.name};var ic=new hc("SHOUT",1200),jc=new hc("SEVERE",1E3),kc=new hc("WARNING",900),lc=new hc("INFO",800),mc=new hc("CONFIG",700);ec.prototype.getChildren=function(){this.c||(this.c={});return this.c};var nc=function(a){return a.g?a.g:a.a?nc(a.a):null};
ec.prototype.log=function(a,b,c){if(a.value>=nc(this).value)for(ca(b)&&(b=b()),a=new cc(a,String(b),this.h),c&&(a.a=c),c="log:"+a.getMessage(),n.console&&(n.console.timeStamp?n.console.timeStamp(c):n.console.markTimeline&&n.console.markTimeline(c)),n.msWriteProfilerMark&&n.msWriteProfilerMark(c),c=this;c;)c=c.a}; var oc={},pc=null,qc=function(){pc||(pc=new ec(""),oc[""]=pc,pc.g=mc)},T=function(a){qc();var b;if(!(b=oc[a])){b=new ec(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=T(a.substr(0,c));c.getChildren()[d]=b;b.a=c;oc[a]=b}return b};
!L("Android")||nb()||L("Firefox")||lb();nb();T("gws.collections.models.IndexedClips");T("gws.collections.models.IndexedFolios");var rc=function(){};q(rc);var sc={0:"c_",1:"f_",2:"d_",3:"g_",4:"lc_",5:"lf_"},tc=function(a){return sc[a]+(839808*a+Math.floor(839808*Math.random())).toString(36)+x().toString(36)};var uc=function(a,b,c){A.call(this,c||"TRANSACTION_COMMIT");this.i=a||0;(a=b)||(rc.B(),a=tc(2));this.h=a;this.c=[];this.l=[]};y(uc,A);var wc=function(a,b,c){a.c.push(b);a.l.push(c);vc(c,b)};uc.prototype.A=function(){return this.h};var xc=!N||wb(),yc=N&&!O("9");!qb||O("528");pb&&O("1.9b")||N&&O("8")||ob&&O("9.5")||qb&&O("528");pb&&!O("8")||N&&O("9");var zc=function(a){zc[" "](a);return a};zc[" "]=function(){};var Ac=function(a,b){A.call(this,a?a.type:"");this.a=this.target=null;this.clientY=this.clientX=0;this.c=this.state=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;if(c&&pb)try{zc(c.nodeName)}catch(d){}this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;this.c=a;a.defaultPrevented&&this.g()}};y(Ac,A); Ac.prototype.g=function(){Ac.H.g.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,yc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var Bc="closure_listenable_"+(1E6*Math.random()|0),Cc=function(a){return!(!a||!a[Bc])},Dc=0;var Ec=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.K=!!d;this.L=e;this.O=++Dc;this.removed=this.J=!1},Fc=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.L=null};var Gc=function(a){this.src=a;this.a={};this.c=0};Gc.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.c++);var g=Hc(a,b,d,e);-1<g?(b=a[g],c||(b.J=!1)):(b=new Ec(b,this.src,f,!!d,e),b.J=c,a.push(b));return b};Gc.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Hc(e,b,c,d);return-1<b?(Fc(e[b]),C.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.c--),!0):!1};
var Ic=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=a.a[c],e=Da(d,b),f;(f=0<=e)&&C.splice.call(d,e,1);f&&(Fc(b),0==a.a[c].length&&(delete a.a[c],a.c--));return f};Gc.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Fc(d[e]);delete this.a[c];this.c--}return b}; var Jc=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Hc(a,c,d,e));return-1<b?a[b]:null},Hc=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.K==!!c&&f.L==d)return e}return-1};
var Kc="closure_lm_"+(1E6*Math.random()|0),Lc={},Mc=0,Nc=function(a,b,c,d,e){if(r(b)){for(var f=0;f<b.length;f++)Nc(a,b[f],c,d,e);return null}c=Oc(c);return Cc(a)?a.listen(b,c,d,e):Pc(a,b,c,!1,d,e)},Pc=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=!!e,h=Qc(a);h||(a[Kc]=h=new Gc(a));c=h.add(b,c,d,e,f);if(c.proxy)return c;d=Rc();c.proxy=d;d.src=a;d.listener=c;a.addEventListener?a.addEventListener(b.toString(),d,g):a.attachEvent(Sc(b.toString()),d);Mc++;return c},Rc=function(){var a=
Tc,b=xc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},Uc=function(a,b,c,d,e){if(r(b)){for(var f=0;f<b.length;f++)Uc(a,b[f],c,d,e);return null}c=Oc(c);return Cc(a)?a.w.add(String(b),c,!0,d,e):Pc(a,b,c,!0,d,e)},Vc=function(a,b,c,d,e){if(r(b))for(var f=0;f<b.length;f++)Vc(a,b[f],c,d,e);else c=Oc(c),Cc(a)?a.unlisten(b,c,d,e):a&&(a=Qc(a))&&(b=Jc(a,b,c,!!d,e))&&Wc(b)},Wc=function(a){if("number"==typeof a||!a||a.removed)return!1;var b=a.src;
if(Cc(b))return Ic(b.w,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.K):b.detachEvent&&b.detachEvent(Sc(c),d);Mc--;(c=Qc(b))?(Ic(c,a),0==c.c&&(c.src=null,b[Kc]=null)):Fc(a);return!0},Sc=function(a){return a in Lc?Lc[a]:Lc[a]="on"+a},Yc=function(a,b,c,d){var e=!0;if(a=Qc(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.K==c&&!f.removed&&(f=Xc(f,d),e=e&&!1!==f)}return e},Xc=function(a,b){var c=a.listener,d=a.L||a.src;a.J&&Wc(a);return c.call(d,
b)},Tc=function(a,b){if(a.removed)return!0;if(!xc){var c;if(!(c=b))a:{c=["window","event"];for(var d=n,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new Ac(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,h=e.length-1;0<=h;h--){c.a=e[h];var k=Yc(e[h],f,!0,c),d=d&&k}for(h=0;h<e.length;h++)c.a=e[h],k=Yc(e[h],
f,!1,c),d=d&&k}return d}return Xc(a,new Ac(b,this))},Qc=function(a){a=a[Kc];return a instanceof Gc?a:null},Zc="__closure_events_fn_"+(1E9*Math.random()>>>0),Oc=function(a){if(ca(a))return a;a[Zc]||(a[Zc]=function(b){return a.handleEvent(b)});return a[Zc]};
var U=function(){z.call(this);this.w=new Gc(this);this.W=this;this.s=null};y(U,z);U.prototype[Bc]=!0;U.prototype.addEventListener=function(a,b,c,d){Nc(this,a,b,c,d)};U.prototype.removeEventListener=function(a,b,c,d){Vc(this,a,b,c,d)};
var vc=function(a,b){var c,d=a.s;if(d)for(c=[];d;d=d.s)c.push(d);var d=a.W,e=b,f=e.type||e;if(u(e))e=new A(e,d);else if(e instanceof A)e.target=e.target||d;else{var g=e,e=new A(f,d);Pa(e,g)}var g=!0,h;if(c)for(var k=c.length-1;0<=k;k--)h=e.a=c[k],g=$c(h,f,!0,e)&&g;h=e.a=d;g=$c(h,f,!0,e)&&g;g=$c(h,f,!1,e)&&g;if(c)for(k=0;k<c.length;k++)h=e.a=c[k],g=$c(h,f,!1,e)&&g};U.prototype.g=function(){U.H.g.call(this);this.w&&this.w.removeAll(void 0);this.s=null};
U.prototype.listen=function(a,b,c,d){return this.w.add(String(a),b,!1,c,d)};U.prototype.unlisten=function(a,b,c,d){return this.w.remove(String(a),b,c,d)};var $c=function(a,b,c,d){b=a.w.a[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.removed&&g.K==c){var h=g.listener,k=g.L||g.src;g.J&&Ic(a.w,g);e=!1!==h.call(k,d)&&e}}return e&&0!=d.U};
var ad=function(){U.call(this)};y(ad,U);var bd=function(a){U.call(this);this.a=a};y(bd,ad);bd.prototype.A=function(){return this.a.D()?B(this.a.D().A()):""};bd.prototype.m=function(){return this.a.m()};var cd=".0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".split(""),dd={},ed;for(ed in cd)dd[cd[ed]]=ed;for(var fd in dd);var V=function(a){z.call(this);this.c=a;this.a={}};y(V,z);var gd=[];V.prototype.listen=function(a,b,c,d){r(b)||(b&&(gd[0]=b.toString()),b=gd);for(var e=0;e<b.length;e++){var f=Nc(a,b[e],c||this.handleEvent,d||!1,this.c||this);if(!f)break;this.a[f.O]=f}return this};var hd=function(a,b,c,d,e,f){if(r(c))for(var g=0;g<c.length;g++)hd(a,b,c[g],d,e,f);else(b=Uc(b,c,d||a.handleEvent,e,f||a.c||a))&&(a.a[b.O]=b)};
V.prototype.unlisten=function(a,b,c,d,e){if(r(b))for(var f=0;f<b.length;f++)this.unlisten(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.c||this,c=Oc(c),d=!!d,b=Cc(a)?Jc(a.w,String(b),c,d,e):a?(a=Qc(a))?Jc(a,b,c,d,e):null:null,b&&(Wc(b),delete this.a[b.O]);return this};V.prototype.removeAll=function(){Ma(this.a,Wc);this.a={}};V.prototype.g=function(){V.H.g.call(this);this.removeAll()};V.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};
var W=function(a,b){this.width=a;this.height=b};W.prototype.clone=function(){return new W(this.width,this.height)};var id=function(a){return a.width*a.height};W.prototype.G=function(){return!id(this)};W.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
var kd=function(a){this.a=a||new Ya;if(!K(this.a)){a=this.a;var b=new J;I(a,2,b)}H(this.a,J,3)||(a=this.a,b=new J,I(a,3,b));this.c=new Q(B(Za(K(this.a))));new Q(jd(this))},jd=function(a){return B(Za(H(a.a,J,3))).replace(/^\/\//,"https://")};kd.prototype.m=function(){return this.a.m()};
var ld=function(a){this.a=a||new bb};ld.prototype.m=function(){return this.a.m()};var md=function(a){this.a=a||new cb};md.prototype.m=function(){return this.a.m()};var nd=function(a){E(this,a,-1,null)};y(nd,D);var Sa=new function(){this.c=71309500;this.a=nd;this.g=0}(function(a,b){var c,d=F(b,1),e=F(b,2),f;if(f=c=b.getLocation())f={latitude:F(c,1),longitude:F(c,2)},a&&(f.V=c);c={Y:d,Z:e,location:f};a&&(c.V=b);return c});nd.prototype.getLocation=function(){return H(this,od,3)};var od=function(a){E(this,a,-1,null)};y(od,D);
var pd=!N||wb(),qd=!pb&&!N||N&&wb()||pb&&O("1.9.1"),rd=N&&!O("9"),sd=N||ob||qb;var td=function(a,b){this.x=void 0!==a?a:0;this.y=void 0!==b?b:0};td.prototype.clone=function(){return new td(this.x,this.y)};td.prototype.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};var vd=function(a,b){Ma(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in ud?a.setAttribute(ud[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})},ud={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},xd=function(a,b,c){var d=arguments,e=document,
f=d[0],g=d[1];if(!pd&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',ua(g.name),'"');if(g.type){f.push(' type="',ua(g.type),'"');var h={};Pa(h,g);delete h.type;g=h}f.push(">");f=f.join("")}f=e.createElement(f);g&&(u(g)?f.className=g:r(g)?f.className=g.join(" "):vd(f,g));2<d.length&&wd(e,f,d);return f},wd=function(a,b,c){function d(c){c&&b.appendChild(u(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];!ba(f)||da(f)&&0<f.nodeType?d(f):Ea(yd(f)?Ia(f):f,d)}},zd=function(a){return qd&&
void 0!=a.children?a.children:Fa(a.childNodes,function(a){return 1==a.nodeType})},Ad=function(a){var b;if(sd&&!(N&&O("9")&&!O("10")&&n.SVGElement&&a instanceof n.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return da(b)&&1==b.nodeType?b:null},Bd=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document},Cd={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Dd={IMG:" ",BR:"\n"},Fd=function(a){if(rd&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Ed(a,b,!0);a=b.join("")}a=
a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");rd||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a},Ed=function(a,b,c){if(!(a.nodeName in Cd))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Dd)b.push(Dd[a.nodeName]);else for(a=a.firstChild;a;)Ed(a,b,c),a=a.nextSibling},yd=function(a){if(a&&"number"==typeof a.length){if(da(a))return"function"==typeof a.item||"string"==typeof a.item;if(ca(a))return"function"== typeof a.item}return!1},Gd=function(a){this.a=a||n.document||document};Gd.prototype.getChildren=zd;
var X=function(a){bd.call(this,a||new eb);this.c=Hd(this);this.o=Id(this);a=H(this.a,Wa,9);!this.l&&a&&(this.l=new Xa(a));this.l=this.l||null;a=this.a;a.a||(a.a={});if(!a.a[3]){for(var b=F(a,3),c=[],d=0;d<b.length;d++)c[d]=new fb(b[d]);a.a[3]=c}b=a.a[3];b==Ra&&(b=a.a[3]=[]);a=b;for(b=0;b<a.length;b++)c=new gb(a[b]),H(c.a,$a,1).A();a=H(this.a,cb,10);!this.C&&a&&(this.C=new md(a));this.C=this.C||null;a=H(this.a,bb,13);!this.I&&a&&(this.I=new ld(a));this.I=this.I||null;new ac;this.A()||(rc.B(),a=tc(0),
this.a.D()||(b=new $a,I(this.a,1,b)),b=this.a.D(),G(b,1,a))};y(X,bd);T("gws.collections.models.ClipModel");X.prototype.clone=function(){var a;a=this.a;a=new a.constructor(Ua(a.c));return new X(a)};var Hd=function(a){var b=H(a.a,Ya,5);!a.c&&b&&(a.c=new kd(b));if(!a.c&&3==F(a.a,4)){var b=B(F(a.l.a,1)).replace(/\//g,"-"),b="https://www.gstatic.com/vd/kp/%s/en/1/image.jpg".replace("%s",b),c=xd("img");c.src=b;c.onload=w(a.M,a,c)}return a.c||null};
X.prototype.M=function(a){var b=new kd,c=a.src,d=H(b.a,J,3);G(d,1,c);new Q(jd(b));c=a.naturalWidth;a=a.naturalHeight;d=H(b.a,J,3);G(d,2,c);c=H(b.a,J,3);G(c,3,a);var c=(a=new uc(3))||new uc,d=this.c&&this.c.m(),e=b.m();d!=e&&(this.c=b,I(this.a,5,b.a),b=x(),G(this.a,8,b),b=Ba(this,203,d||"",e,c),wc(c,b,this),c!=a&&0<c.c.length&&vc(this,c))};var Id=function(a){var b=H(a.a,ab,6);!a.o&&b&&(a.o=new Yb(b));return a.o||null};X.prototype.getTitle=function(){return Id(this)?Id(this).getTitle().toString():""};
X.prototype.setTitle=function(a,b){var c=b||new uc;if(Id(this).getTitle()==a)return!1;var d=Id(this).m(),e=Id(this);e.setTitle(a);var f=x();G(this.a,8,f);d=Ba(this,204,d,e.m(),c);wc(c,d,this);c!=b&&0<c.c.length&&vc(this,c);return!0};var Jd=function(a,b){var c=new uc,d=F(a.a,4);F(a.a,4)!=b&&(G(a.a,4,b),d=Ba(a,206,""+d,""+b,c),wc(c,d,a),void 0!=c&&0<c.c.length&&vc(a,c))};X.prototype.toString=function(){return"ClipModel:"+this.A()}; X.prototype.getLocation=function(){var a=Ta(this.a);return a&&(a=a.getLocation())?B(F(a,1).toFixed(4)+","+F(a,2).toFixed(4)):""};
var Kd=function(a){var b;do b=a,a=-1!=a.indexOf("&")?"document"in n?wa(a):xa(a):a;while(a!=b);return a};var Ld=function(a){z.call(this);this.l=a;this.a={};this.c={}};y(Ld,z);Ld.prototype.g=function(){this.unlisten();Ld.H.g.call(this)};Ld.prototype.listen=function(a,b){var c=w(b,this.l);a.addListener(c);var d=ga(a);d in this.a?this.c[d].add(c):(this.a[d]=a,this.c[d]=new ac([c]));return this};Ld.prototype.unlisten=function(a){if(a){var b=ga(a);if(b in this.a){var c=this.c[b].v();Ea(c,a.removeListener,a);delete this.c[b];delete this.a[b]}}else Ma(this.a,this.unlisten,this)};
var Md=function(){U.call(this);this.I=new V(this);ka(this,ja(la,this.I))};y(Md,U);Md.prototype.c=function(a){this.s=a};var Nd=function(){this.a=["ad","advertisement","ads","sponsor","sponsored"]};Nd.prototype.filter=function(a){for(;a;){var b;a.classList?b=a.classList:(b=a.className,b=u(b)&&b.match(/\S+/g)||[]);for(var c=0;c<b.length;++c)for(var d=b[c].split(/\W+/),e=0;e<d.length;++e)if(0<=Da(this.a,d[e].toLowerCase()))return!1;a=Ad(a)}return!0};
var Od=function(a){this.a=a},Pd=function(a,b){return a==b?0:a.a-b.a};var Qd=function(){this.a=[]};Qd.prototype.filter=function(a){for(var b=0;b<this.a.length;++b)if(!this.a[b].filter(a))return!1;return!0};var Rd=function(a,b){var c=a.c(b);if(0==c.length)return null;for(var d=c[0],e=1;e<c.length;++e){var f=c[e];f.a>d.a&&(d=f)}return d};Qd.prototype.c=function(a){return Y(this,a.getElementsByTagName("*"))};var Y=function(a,b,c){for(var d=[],e=b.length,f=0;f<e;++f){var g=a.g(b[f],c);g&&d.push(g)}return d};Qd.prototype.g=function(){return null};
var Sd=function(a,b,c,d){this.a=a;this.c=b;this.g=c;this.h=d};y(Sd,Od);var Z=function(a,b){var c=Bd(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b)||"":""},Td=function(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}N&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b},Vd=function(a){var b=Ud;if("none"!=(Z(a,"display")||(a.currentStyle?a.currentStyle.display:
null)||a.style&&a.style.display))return b(a);var c=a.style,d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=f;c.visibility=e;return a},Ud=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=qb&&!b&&!c;return(void 0===b||d)&&a.getBoundingClientRect?(a=Td(a),new W(a.right-a.left,a.bottom-a.top)):new W(b,c)};
var Wd=function(){};Wd.prototype.filter=function(a){for(;a;){if("none"==Z(a,"display"))return!1;var b=Vd(a);if("hidden"==Z(a,"overflow")&&b.G()||"hidden"==Z(a,"visibility"))return!1;a=Ad(a)}return!0};var Xd=function(){this.a=[];this.a.push(new Nd);this.a.push(new Wd)};y(Xd,Qd);q(Xd);var Yd=T("image.collections.extension.domextractor.DocumentImageExtractor"),Zd={".gif":.5},$d=function(){this.T=0;this.P={}};Xd.prototype.c=function(a){return Y(this,a.getElementsByTagName("*"),new $d)};
Xd.prototype.g=function(a,b){var c=null;switch(a.tagName.toLowerCase()){case "meta":c=ae(a,1,"property","og:image","content")||ae(a,.9,"name","msapplication-tileimage","content")||ae(a,.8,"name","twitter:image","content")||be(a);break;case "link":c=ae(a,.7,"rel","apple-touch-icon","href")||ae(a,.6,"rel","image_src","href")||be(a);break;case "img":if(this.filter(a))a:{if((c=a.src)&&0!=c.lastIndexOf("data:",0)){var d=new W(a.naturalWidth,a.naturalHeight),e=Vd(a),f=id(d)<id(e)?d:e;if(f.width&&f.height){f=
ce(a);c=new Sd(f,c,d,e);break a}}c=null}break;default:if(this.filter(a)&&30>b.T){a:{c=Z(a,"background-image");d=Z(a,"background-repeat");e=Z(a,"background-size");if(d=c&&("no-repeat"==d||"cover"==e)&&0==c.lastIndexOf("url(",0))d=c.length-1,d=0<=d&&c.indexOf(")",d)==d;if(d&&(c=c.substr(4,c.length-5))&&0!=c.lastIndexOf("data:",0)&&(d=Vd(a),d.width&&d.height)){for(var e=ce(a),f=zd(a),g=0;g<f.length;++g){var h=f[g];if("none"!=Z(h,"display")&&id(Vd(h))>.1*id(d)){e*=.1;break}}c=new Sd(e,c,void 0,d);break a}c=
null}c&&++b.T}}if(!c)return null;e=c.h||c.g;if(c.c!=document.location.href&&(100>e.width||100>e.height))return null;d=c.a;d/=1+Math.exp(-1E-5*id(e));e=e.width/e.height;1>e&&(e=1/e);2<e&&(d*=.8);e=c.c;try{var k=Bd(a).documentURI,f=e;k instanceof Q||(k=Ub(k));f instanceof Q||(f=Ub(f));var g=k,k=f,p=g.clone(),m=!!k.g;m?Jb(p,k.g):m=!!k.o;m?p.o=k.o:m=!!k.c;m?p.c=k.c:m=null!=k.s;var t=k.a;if(m)Kb(p,k.s);else if(m=!!k.a){if("/"!=t.charAt(0))if(g.c&&!g.a)t="/"+t;else{var v=p.a.lastIndexOf("/");-1!=v&&(t=
p.a.substr(0,v+1)+t)}v=t;if(".."==v||"."==v)t="";else if(-1!=v.indexOf("./")||-1!=v.indexOf("/.")){for(var fc=0==v.lastIndexOf("/",0),kb=v.split("/"),v=[],f=0;f<kb.length;){var gc=kb[f++];"."==gc?fc&&f==kb.length&&v.push(""):".."==gc?((1<v.length||1==v.length&&""!=v[0])&&v.pop(),fc&&f==kb.length&&v.push("")):(v.push(gc),fc=!0)}t=v.join("/")}else t=v}m?p.a=t:m=""!==k.l.toString();m?Lb(p,Mb(k.l.toString())):m=!!k.h;m&&(p.h=k.h);e=p.toString()}catch(Ke){return Yd&&Yd.log(lc,"Cannot resolve url: "+e,
void 0),null}p=B(Bb(Cb(e)[5]||null));m=p.lastIndexOf(".");0<m&&(p=Zd[p.slice(m)])&&(d*=p);if(e in b.P&&b.P[e]>d)return null;b.P[e]=d;return new Sd(d,e,c.g,c.h)};
var ae=function(a,b,c,d,e){if(B(a.getAttribute(c)).toLowerCase()==d.toLowerCase()){c=a.getAttribute(e);if(!c||0==c.lastIndexOf("data:",0))return null;d=za(a.getAttribute("data-google-stars-image-width"));e=za(a.getAttribute("data-google-stars-image-height"));if(d&&e)return a=Bd(a),"/"!=Bb(Cb(a.documentURI)[5]||null)&&-1==a.body.innerHTML.indexOf(c)&&(b*=.5),new Sd(b,c,new W(d,e))}return null},be=function(a){var b=a.getAttribute("itemprop");if(b&&"thumbnailurl"==b.toLowerCase()){b=a.getAttribute("href")||
a.getAttribute("content");if(!b||0==b.lastIndexOf("data:",0))return null;var c=za(a.getAttribute("data-google-stars-image-width"));a=za(a.getAttribute("data-google-stars-image-height"));if(c&&a)return new Sd(.55,b,new W(c,a))}return null},ce=function(a){var b=Bd(a),c=new td(0,0),d;d=b?Bd(b):document;var e;(e=!N||wb())||(e="CSS1Compat"==(d?new Gd(Bd(d)):Ca||(Ca=new Gd)).a.compatMode);a!=(e?d.documentElement:d.body)&&(a=Td(a),d=(b?new Gd(Bd(b)):Ca||(Ca=new Gd)).a,b=qb||"CSS1Compat"!=d.compatMode?d.body||
d.documentElement:d.documentElement,d=d.parentWindow||d.defaultView,b=N&&O("10")&&d.pageYOffset!=b.scrollTop?new td(b.scrollLeft,b.scrollTop):new td(d.pageXOffset||b.scrollLeft,d.pageYOffset||b.scrollTop),c.x=a.left+b.x,c.y=a.top+b.y);c=c.y;return 2E3<c?0:1/(1+Math.exp(.001*c))};
var de=function(a,b){this.a=a;this.c=b};y(de,Od);var ee=function(){this.a=[]};y(ee,Qd);q(ee);ee.prototype.c=function(a){var b=Y(this,a.getElementsByTagName("meta"));b.push(fe(a));if(a=a?a.parentWindow||a.defaultView:window)a=a.getSelection().toString(),0<a.length&&b.push(new de(1,a));return b};
ee.prototype.g=function(a){var b=0,c="";switch(a.tagName.toLowerCase()){case "meta":var d=a.getAttribute("name"),e=a.getAttribute("property");if(e&&"og:description"==e.toLowerCase())b=.9;else if(d)switch(d.toLowerCase()){case "twitter:description":b=.8;break;case "description":b=.7;break;case "msapplication-tooltip":b=.6}0<b&&(c=a.getAttribute("content")||"")}c=Kd(c);c=c.replace(/<[^<>]*?>/g,"");c=c.trim();return 5<c.length?(a=c,1024<a.length&&(a=a.substring(0,1021)+"..."),new de(b,a)):null};
var fe=function(a){if(a.body){var b="",c="",d=0;a=a.body.innerText.replace(/(\r\n|\r|\n)/g,"\n");for(var e=a.split("\n"),f=0;f<e.length;++f){for(var b=e[f].replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,""),g=b.split(" "),h=g.length,k,p=k=0;p<b.length;++p)!/[^a-zA-Z]/.test(b.charAt(p))&&++k;if(p=64<=b.length&&8<=h&&k>=.4*b.length){for(var m=p=0;m<b.length;++m){var t=b.charAt(m);/[^a-zA-Z0-9]/.test(t)&&/[^\t\n\r ]/.test(t)&&++p}p=0<p}if(p&&24>=ge(g))break;k>=.4*b.length&&h>d&&24>=ge(g)&&(c=b,d=h); b=""}0==b.length&&20<c.length&&4<=d&&(b=c);a=a.replace(/[\t\r\n ]+/g," ").replace(/^[\t\r\n ]+|[\t\r\n ]+$/g,"");return new de(.1,b||a.substring(0,1024))}return null},ge=function(a){for(var b=0,c=0;c<a.length;++c)b=Math.max(a[c].length,b);return b};
var he=function(a,b){this.a=a;this.c=b};y(he,Od);var ie=function(a){return a.c};var je=function(a,b,c){this.a=a;this.g=b;this.c=c};y(je,Od);var ke=function(a,b,c,d){this.g=a;this.a=b;this.c=c;this.h=d};ke.prototype.getTitle=function(){return this.g};var le=function(){this.a=[]};y(le,Qd);q(le);le.prototype.c=function(a){var b=Y(this,a.getElementsByTagName("meta")).concat(Y(this,a.getElementsByTagName("title"))),c=Y(this,a.getElementsByTagName("h1"));0<c.length?1==c.length&&(b=Ha(b,c)):(c=Y(this,a.getElementsByTagName("h2")),0<c.length?1==c.length&&(b=Ha(b,c)):(c=Y(this,a.getElementsByTagName("h3")),0<c.length&&1==c.length&&(b=Ha(b,c))));a.title&&b.push(new he(1,a.title));b.push(new he(.1,a.documentURI));return b};
le.prototype.g=function(a){var b=0,c="";switch(a.tagName.toLowerCase()){case "title":b=.5;c=Fd(a);break;case "h1":b=.4;c=Fd(a);break;case "h2":b=.3;c=Fd(a);break;case "h3":b=.2;c=Fd(a);break;case "meta":var d=a.getAttribute("name"),e=a.getAttribute("property");if(e&&"og:title"==e.toLowerCase())b=.9;else if(d)switch(d.toLowerCase()){case "application-name":b=.8;break;case "twitter:title":b=.7;break;case "title":b=.6}0<b&&(c=a.getAttribute("content")||"")}c=Kd(c.trim());return 1<c.length?new he(b,c): null};
var me=function(){this.a=[]};y(me,Qd);q(me);me.prototype.g=function(a){switch(a.tagName.toLowerCase()){case "meta":var b;a:{if("og:video"==B(a.getAttribute("property")).toLowerCase()){b=a.getAttribute("content");var c=za(a.getAttribute("data-google-stars-video-width"));a=za(a.getAttribute("data-google-stars-video-height"));if(b&&0<c&&0<a){b=new je(1,b,new W(c,a));break a}}b=null}return b}return null};
var ne=function(a,b,c,d){this.g=a||le.B();this.c=b||ee.B();this.a=c||Xd.B();this.h=d||me.B()};q(ne);var oe=function(){var a=ne.B(),b=document,c=Rd(a.g,b),d=Rd(a.c,b),e=a.a.c(b),a=Rd(a.h,b);Ja(e,function(a){return a.c});return new ke(c,d,e,a)};var pe=function(a){if(!ca(a))if(a&&"function"==typeof a.handleEvent)a=w(a.handleEvent,a);else throw Error("Invalid listener argument");n.setTimeout(a,5E3)};var qe=function(){this.a=0;this.h=new V(this);this.g=Promise.resolve();this.c=null},re=T("image.collections.extension.DomController"),se=function(a){if(0==a.a){var b=document,c=b.getElementsByTagName("meta"),b=b.getElementsByTagName("link");a.a=c.length+b.length;0<a.a?(a.g=new Promise(w(function(a){this.c=a},a)),Ea(c,a.o,a),Ea(b,a.l,a),pe(a.c)):a.g=Promise.resolve()}return a.g};
qe.prototype.o=function(a){var b="";if(a.hasAttribute("property"))switch(a.getAttribute("property").toLowerCase()){case "og:image":var b=a.getAttribute("content"),c=zd(Ad(a)),d=te(c,"og:image:width"),c=te(c,"og:image:height");0<d&&0<c&&(a.setAttribute("data-google-stars-image-width",d),a.setAttribute("data-google-stars-image-height",c));break;case "og:video":c=zd(Ad(a)),d=te(c,"og:video:width"),c=te(c,"og:video:height"),0<d&&0<c&&(a.setAttribute("data-google-stars-video-width",d),a.setAttribute("data-google-stars-video-height",
c))}else if(a.hasAttribute("name"))switch(a.getAttribute("name").toLowerCase()){case "msapplication-tileimage":case "twitter:image":b=a.getAttribute("content")}else if(a.hasAttribute("itemprop"))switch(a.getAttribute("itemprop").toLowerCase()){case "thumbnailurl":b=a.getAttribute("href")||a.getAttribute("content")}ue(this,b,a)};
qe.prototype.l=function(a){var b="";if(a.hasAttribute("rel"))switch(a.getAttribute("rel").toLowerCase()){case "apple-touch-icon-precomposed":case "apple-touch-icon":case "image_src":b=a.getAttribute("href")}else if(a.hasAttribute("itemprop"))switch(a.getAttribute("itemprop").toLowerCase()){case "thumbnailurl":b=a.getAttribute("href")||a.getAttribute("content")}ue(this,b,a)};
var te=function(a,b){for(var c=0;c<a.length;++c){var d=a[c];if(d.hasAttribute("property")&&d.getAttribute("property").toLowerCase()==b&&d.hasAttribute("content"))return d.getAttribute("content")}return""},ue=function(a,b,c){if(!b||c.hasAttribute("data-google-stars-image-width")&&c.hasAttribute("data-google-stars-image-height"))0==--a.a&&a.c();else{var d=w(a.s,a,c);c=new Image;d=w(a.i,a,d);hd(a.h,c,["load","error"],d,void 0);c.src=b}};
qe.prototype.i=function(a,b){var c=b.target;"load"==b.type?a(c.naturalWidth,c.naturalHeight):re&&re.log(kc,"Failed to load image "+c.src,void 0);0==--this.a&&this.c()};qe.prototype.s=function(a,b,c){a.setAttribute("data-google-stars-image-width",b);a.setAttribute("data-google-stars-image-height",c)};
var ve=function(){Md.call(this);this.a=null;this.o=new qe;this.l=new Ld(this);ka(this,ja(la,this.l))};y(ve,Md);var we=T("image.collections.extension.ContentController");ve.prototype.c=function(a){ve.H.c.call(this,a);this.l.listen(chrome.runtime.onMessage,this.M)};
ve.prototype.M=function(a,b,c){c({received:"true"});switch(a.type){case "collect_page":if(null===this.a){b=a.clipId;c=a.userId;a=new $a;G(a,1,b);G(a,2,c);b=new eb;I(b,1,a);a=x();G(b,7,a);G(b,8,a);this.a=new X(b);b=document.documentURI;/\.(jpg|jpeg|png|gif|bmp|svg|tiff)$/i.test(b)?Jd(this.a,1):Jd(this.a,2);a=new Yb;try{Ub(b)}catch(d){b=encodeURI(b)}try{Ub(b)}catch(e){b=""}G(a.a,3,b);b=this.a;b.o=a;I(b.a,6,a.a);se(this.o).then(w(this.C,this,!0))}else we&&we.log(kc,"Clip is already being created",void 0);
break;case "get_salient_images":se(this.o).then(w(this.C,this,!1));break;default:we&&we.log(jc,"Invalid message type: "+a.type,void 0)}};
ve.prototype.C=function(a){var b=oe(),c=b.c;c.sort(Pd||Ka);for(var d=[],e=null,f=0;f<c.length;f++){var g=e=new kd,h=c[f].c;g.c=null;try{var k=K(g.a);G(k,1,h);g.c=new Q(B(Za(K(g.a))))}catch(p){h=K(g.a),G(h,1,void 0),h=K(g.a),G(h,2,void 0),h=K(g.a),G(h,3,void 0)}g.c&&F(g.a,6)&&G(g.a,6,!1);var m=c[f].g;if(m){var g=e,h=m.width,m=m.height,t=K(g.a);G(t,2,h);g=K(g.a);G(g,3,m)}d.unshift(e.m())}if(a){!Hd(this.a)&&e&&(a=this.a,c=e,a.c=c,I(a.a,5,c.a),c=x(),G(a.a,8,c));a=Id(this.a);!a.getTitle()&&b.getTitle()&&
a.setTitle(ie(b.getTitle()));!B(F(a.a,2))&&b.a&&G(a.a,2,b.a.c);if(a=b.h)Jd(this.a,4),b=new md,G(b.a,1,a.g),c=a.c.height,G(b.a,2,a.c.width),G(b.a,3,c),a=this.a,a.C=b,I(a.a,10,b.a);chrome.runtime.sendMessage({type:"created_clip",clipData:this.a.m(),images:d});this.a=null}else chrome.runtime.sendMessage({type:"salient_images_found",images:d})};
var xe=function(){this.a=x()},ye=new xe;xe.prototype.set=function(a){this.a=a};xe.prototype.reset=function(){this.set(x())};xe.prototype.get=function(){return this.a};var ze=function(a){this.h=a||"";this.i=ye};ze.prototype.a=!0;ze.prototype.c=!0;ze.prototype.g=!1;var Ae=function(a){return 10>a?"0"+a:String(a)},Be=function(a,b){var c=(a.g-b)/1E3,d=c.toFixed(3),e=0;if(1>c)e=2;else for(;100>c;)e++,c*=10;for(;0<e--;)d=" "+d;return d},Ce=function(a){ze.call(this,a)};y(Ce,ze);
var De=function(){w(this.h,this);this.a=new Ce;this.a.c=!1;this.a.g=!1;this.c=this.a.a=!1;this.g="";this.i={}};
De.prototype.h=function(a){if(!this.i[a.c]){var b;b=this.a;var c=[];c.push(b.h," ");if(b.c){var d=new Date(a.g);c.push("[",Ae(d.getFullYear()-2E3)+Ae(d.getMonth()+1)+Ae(d.getDate())+" "+Ae(d.getHours())+":"+Ae(d.getMinutes())+":"+Ae(d.getSeconds())+"."+Ae(Math.floor(d.getMilliseconds()/10)),"] ")}c.push("[",Be(a,b.i.get()),"s] ");c.push("[",a.c,"] ");c.push(a.getMessage());b.g&&(d=a.a)&&c.push("\n",d instanceof Error?d.message:d.toString());b.a&&c.push("\n");b=c.join("");if(c=Ee)switch(a.h){case ic:Fe(c, "info",b);break;case jc:Fe(c,"error",b);break;case kc:Fe(c,"warn",b);break;default:Fe(c,"debug",b)}else this.g+=b}};var Ee=n.console,Fe=function(a,b,c){if(a[b])a[b](c);else a.log(c)};
var Ge=function(){U.call(this);this.a=new ve;ka(this,ja(la,this.a))};y(Ge,U);q(Ge);var He=new De;0!=He.c&&(qc(),He.c=!1);var Ie=T("image.collections.extension.Content"),Je=Ge.B();Ie&&Ie.log(lc,"Initializing extension content",void 0);Je.a.c(Je);window.full_script_injected=!0;

}catch(e){_DumpException(e)}
// Google Inc.
