# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1412112635);
user_pref("app.update.lastUpdateTime.background-update-timer", 1412112515);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1412112834);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1412112275);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1412112395);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 6);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140324101726");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 7776);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage", "https://workforcenow.adp.com/public/index.htm");
user_pref("browser.startup.homepage_override.buildID", "20140324101726");
user_pref("browser.startup.homepage_override.mstone", "29.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"bookmarks\":2}");
user_pref("browser.tabs.warnOnClose", false);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1412198538993");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1412112138993");
user_pref("datareporting.sessions.current.activeTicks", 31);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 15706);
user_pref("datareporting.sessions.current.main", 5406);
user_pref("datareporting.sessions.current.sessionRestored", 10505);
user_pref("datareporting.sessions.current.startTime", "1412112705668");
user_pref("datareporting.sessions.current.totalTime", 293);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1412112131785,\"a\":3,\"t\":20,\"c\":true,\"m\":1781,\"fp\":2769,\"sr\":10705}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1412112154079,\"a\":13,\"t\":536,\"c\":true,\"m\":640,\"fp\":2082,\"sr\":2233}");
user_pref("dom.disable_open_during_load", false);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:29.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20140527.01.3");
user_pref("extensions.installCache", "[{\"name\":\"winreg-app-global\",\"addons\":{\"{20a82645-c095-46ed-80e3-08825760534b}\":{\"descriptor\":\"c:\\\\WINDOWS\\\\Microsoft.NET\\\\Framework\\\\v3.5\\\\Windows Presentation Foundation\\\\DotNetAssistantExtension\",\"mtime\":1395941428593,\"rdfTime\":1232736520000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1395921063281,\"rdfTime\":1395921062968}}}]");
user_pref("extensions.lastAppVersion", "29.0");
user_pref("extensions.lastPlatformVersion", "29.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20140324101726");
user_pref("gecko.mstone", "29.0");
user_pref("idle.lastDailyNotification", 1412112442);
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1412112442);
user_pref("places.history.expiration.transient_current_max_pages", 53222);
user_pref("plugin.disable_full_page_plugin_for_types", "");
user_pref("plugin.importedState", true);
user_pref("pref.downloads.disable_button.edit_actions", false);
user_pref("privacy.sanitize.didShutdownSanitize", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
user_pref("services.sync.fxaccounts.enabled", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1412112442);
user_pref("toolkit.startup.last_success", 1412112711);
user_pref("toolkit.telemetry.previousBuildID", "20140324101726");
