#!/bin/bash
# Script:      local_stagger_nightly.sh
# Author:      Matt Gonzales
# Usage:       Calls nightly.sh on hal2.
# Description: Delays nightly.sh depending on location
#              and random number generated by local machine.
# Wiki URL:    https://sites.google.com/a/connexionpoint.com/it-support/linux/nightly-cron-functions-and-scripts


### Location checks
declare -A locations
locations=(
        [208]=0-21600     # SAT
        [209]=0-21600 
        [210]=0-21600  
        [211]=0-21600  
    )

for i in ${!locations[@]}; do
    hostname -I | grep "192.168.$i"
    if [[ "$?" == "0" ]]; then
        echo "subnet is: $i"
        seconds_range=${locations[$i]}
        site=$i
        echo "seconds_range: $seconds_range"
        break
    fi
done

### Variables
sleep_time=$(shuf -i $seconds_range -n 1)

### Script
printf "Cron will start in: $sleep_time seconds.\n\n"

for (( i=$sleep_time; i > 0; i--))
do
    echo $i
    sleep 1
done

/usr/src/IT_Files/Linux/cron/nightly.sh
