#!/bin/bash
# Script:      stagger_nightly.sh
# Author:      Matt Gonzales
# Usage:       Source include for nightly.sh
# Description: Delays nightly.sh depending on location
#              and random number generated by local machine.
# Wiki URL:    https://sites.google.com/a/connexionpoint.com/it-support/linux/nightly-cron-functions-and-scripts


### Location checks
declare -A locations
locations=(
        [0]=0-5          # HQ
        [1]=0-5    
        [8]=0-1200       # Provo
        [9]=0-1200   
        [17]=1200-2400   # Roy
        [19]=1200-2400   
        [104]=2400-4200  # SLC
        [105]=2400-4200  
        [106]=2400-4200  
        [107]=2400-4200  
        [208]=0-2        # SAT
        [209]=0-2
        [210]=0-2
        [211]=0-2
    )

for i in ${!locations[@]}; do
    hostname -I | grep "192.168.$i"
    if [[ "$?" == "0" ]]; then
        echo "subnet is: $i"
        seconds_range=${locations[$i]}
        site=$i
        echo "seconds_range: $seconds_range"
        break
    fi
done

### Variables
sleep_time=$(shuf -i $seconds_range -n 1)

### Script
printf "Cron will start in: $sleep_time seconds.\n\n"

for (( i=$sleep_time; i > 0; i--))
do
    echo $i
    sleep 1
done
