# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1410994510);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1410994629);
user_pref("app.update.service.enabled", false);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.formfill.enable", false);
user_pref("browser.migration.version", 10);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.rights.3.shown", true);
user_pref("browser.slowStartup.averageTime", 4685);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage", "https://workforcenow.adp.com/public/index.htm");
user_pref("browser.startup.homepage_override.buildID", "20130514181517");
user_pref("browser.startup.homepage_override.mstone", "22.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"bookmarks\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1411080909466");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1410994509466");
user_pref("datareporting.sessions.current.activeTicks", 2);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 891);
user_pref("datareporting.sessions.current.main", 141);
user_pref("datareporting.sessions.current.sessionRestored", 969);
user_pref("datareporting.sessions.current.startTime", "1410994690046");
user_pref("datareporting.sessions.current.totalTime", 7);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1410994505796,\"a\":36,\"t\":183,\"c\":true,\"m\":125,\"fp\":750,\"sr\":8344}");
user_pref("dom.disable_open_during_load", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:22.0");
user_pref("extensions.installCache", "[{\"name\":\"winreg-app-global\",\"addons\":{\"{20a82645-c095-46ed-80e3-08825760534b}\":{\"descriptor\":\"c:\\\\WINDOWS\\\\Microsoft.NET\\\\Framework\\\\v3.5\\\\Windows Presentation Foundation\\\\DotNetAssistantExtension\",\"mtime\":1349091884688,\"rdfTime\":1232736520000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1409260235875,\"rdfTime\":1368586310000}}}]");
user_pref("extensions.lastAppVersion", "22.0");
user_pref("extensions.lastPlatformVersion", "22.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20130514181517");
user_pref("gecko.mstone", "22.0");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 26617);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1410994690);
user_pref("toolkit.telemetry.previousBuildID", "20130514181517");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1413586515);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
