# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1406314876);
user_pref("app.update.lastUpdateTime.background-update-timer", 1406314756);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1406314996);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1406314466);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1406314636);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140825202822");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 4402);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage", "https://workforcenow.adp.com/public/index.htm");
user_pref("browser.startup.homepage_override.buildID", "20140825202822");
user_pref("browser.startup.homepage_override.mstone", "32.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"bookmarks\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1406400746002");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1406314346001");
user_pref("datareporting.sessions.current.activeTicks", 5);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1031);
user_pref("datareporting.sessions.current.main", 594);
user_pref("datareporting.sessions.current.sessionRestored", 2372);
user_pref("datareporting.sessions.current.startTime", "1411091710789");
user_pref("datareporting.sessions.current.totalTime", 30);
user_pref("datareporting.sessions.currentIndex", 3);
user_pref("datareporting.sessions.previous.0", "{\"s\":1406314341076,\"a\":29,\"t\":150,\"c\":true,\"m\":1703,\"fp\":2263,\"sr\":8580}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1406314515017,\"a\":22,\"t\":484,\"c\":true,\"m\":421,\"fp\":2009,\"sr\":2157}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1406315002072,\"a\":6,\"t\":27,\"c\":true,\"m\":1125,\"fp\":2384,\"sr\":2599}");
user_pref("dom.disable_open_during_load", false);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:32.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1411091712);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20140527.01.3");
user_pref("extensions.installCache", "[{\"name\":\"winreg-app-global\",\"addons\":{\"{20a82645-c095-46ed-80e3-08825760534b}\":{\"descriptor\":\"c:\\\\WINDOWS\\\\Microsoft.NET\\\\Framework\\\\v3.5\\\\Windows Presentation Foundation\\\\DotNetAssistantExtension\",\"mtime\":1409848450859,\"rdfTime\":1232736520000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1409776685578,\"rdfTime\":1409031461000}}}]");
user_pref("extensions.lastAppVersion", "32.0");
user_pref("extensions.lastPlatformVersion", "32.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20140825202822");
user_pref("gecko.mstone", "32.0");
user_pref("idle.lastDailyNotification", 1406314796);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1406314797);
user_pref("places.history.expiration.transient_current_max_pages", 52784);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.fxaccounts.enabled", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("signon.rememberSignons", false);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1406314796);
user_pref("toolkit.startup.last_success", 1411091711);
user_pref("toolkit.telemetry.previousBuildID", "20140825202822");
