# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1405182965);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1405183085);
user_pref("app.update.service.enabled", false);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.restore_on_demand", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140324101726");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 5524);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage", "https://workforcenow.adp.com/public/index.htm");
user_pref("browser.startup.homepage_override.buildID", "20140324101726");
user_pref("browser.startup.homepage_override.mstone", "29.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"bookmarks\":0}");
user_pref("browser.uitour.whitelist.add.260", "");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1405269244848");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1410562255271");
user_pref("datareporting.policy.firstRunTime", "1405182844848");
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.main", 1031);
user_pref("datareporting.sessions.current.startTime", "1410563609655");
user_pref("datareporting.sessions.current.totalTime", 5);
user_pref("datareporting.sessions.currentIndex", 4);
user_pref("datareporting.sessions.previous.0", "{\"s\":1405182840415,\"a\":50,\"t\":262,\"c\":true,\"m\":891,\"fp\":1244,\"sr\":6415}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1405645136316,\"a\":12,\"t\":63,\"c\":true,\"m\":3360,\"fp\":5444,\"sr\":6065}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1406167001810,\"a\":18,\"t\":98,\"c\":true,\"m\":2077,\"fp\":3413,\"sr\":5162}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1410562186623,\"a\":16,\"t\":85,\"c\":true,\"m\":4228,\"fp\":6892,\"sr\":7376}");
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:29.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"winreg-app-global\",\"addons\":{\"{20a82645-c095-46ed-80e3-08825760534b}\":{\"descriptor\":\"c:\\\\WINDOWS\\\\Microsoft.NET\\\\Framework\\\\v3.5\\\\Windows Presentation Foundation\\\\DotNetAssistantExtension\",\"mtime\":1395941428593,\"rdfTime\":1232736520000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1395921063281,\"rdfTime\":1395921062968}}}]");
user_pref("extensions.lastAppVersion", "29.0");
user_pref("extensions.lastPlatformVersion", "29.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20140324101726");
user_pref("gecko.mstone", "29.0");
user_pref("gfx.blacklist.direct2d", 3);
user_pref("gfx.blacklist.layers.direct3d10", 3);
user_pref("gfx.blacklist.layers.direct3d10-1", 3);
user_pref("gfx.blacklist.layers.direct3d9", 3);
user_pref("gfx.blacklist.layers.opengl", 3);
user_pref("gfx.blacklist.stagefright", 3);
user_pref("gfx.blacklist.suggested-driver-version", "6.1400.1000.5218");
user_pref("gfx.blacklist.webgl.angle", 3);
user_pref("gfx.blacklist.webgl.msaa", 3);
user_pref("gfx.blacklist.webgl.opengl", 3);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 53222);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.fxaccounts.enabled", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.rememberSignons", false);
user_pref("toolkit.startup.last_success", 1410563610);
user_pref("toolkit.telemetry.previousBuildID", "20140324101726");
